### PR TITLE
Added trade-off plot

### PR DESCRIPTION
**Pull request by chen-chen-stat**

### CODE REVIEW

**Comment by chen-chen-stat** [comment]
@Lovemore-Gakava The trade-off plot is ready for your review.

**Comment by Lovemore-Gakava** [comment]
@chen-chen-stat thanks for setting this up. I have added a few comments regarding adding the argument zscore and/ tscore in the functions to make them dynamic. We will need to update the readme to include the new figure. Otherwise all looks great.

**Comment by chen-chen-stat** [comment]
@Lovemore-Gakava Thank you for your previous review and comments. The updated PR is ready for your review.

**Review by Lovemore-Gakava — APPROVED** [review]

**Review by Lovemore-Gakava — APPROVED** [review]
Making the z score be an argument will be done when we do refactoring.

**Pull request merged**
